Alternative unrachable answers
hmcts/nfdiv-frontend pull request #1418
Opened 2021-11-09 15:30 UTC by velimd

### JIRA link ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-11-09 15:43 UTC, linusnorton approved these changes

2021-11-12 12:37 UTC, benouaer approved these changes

2021-11-12 12:49 UTC, linusnorton requested changes
Sorry, not a fan of passing the state through

2021-11-12 13:12 UTC, linusnorton approved these changes

2021-11-12 14:16 UTC, merged