Nfdiv 293 privacy statements
hmcts/nfdiv-frontend pull request #61
Opened 2021-01-13 13:53 UTC by SarahLittlejohn

### JIRA link ###
https://tools.hmcts.net/jira/browse/NFDIV-293

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2021-01-13 14:00 UTC, linusnorton requested changes
Please remove all the `| safe` filters

2021-01-14 09:36 UTC, linusnorton approved these changes

2021-01-14 13:53 UTC, velimd approved these changes

2021-01-14 13:53 UTC, velimd commented on src/main/steps/common/page.njk
> +  {{ govukFooter({
this needs to be imported, I've also included but i think your changes should go in first so i believe its best to include it.

2021-02-17 19:55 UTC, merged